name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup python for cwltool
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.x'
    - name: Install cwltool
      run: pip install cwltool
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install pup
      run: |
        curl -LO https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
        unzip pup_v0.4.0_linux_amd64.zip
        sudo install -m 755 pup /usr/local/bin
    - name: Run tests
      id: run-tests
      uses: common-workflow-lab/run-tests@v1
      with:
        test-list: test.yml
        runner: cwltool
        timeout: 30
